# Generated by Django 4.2.2 on 2023-06-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('ratings', models.IntegerField(choices=[(4, 4), (5, 5), (3, 3), (2, 2), (1, 1)])),
                ('content', models.TextField()),
                ('dt_created', models.DateTimeField()),
                ('imgfile', models.ImageField(upload_to='review_images/')),
                ('domain_clf', models.CharField(max_length=15)),
                ('objects_clf', models.TextField()),
            ],
        ),
    ]
