# Generated by Django 4.2.2 on 2023-06-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_models',
            name='dt_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
