# Generated by Django 4.2.2 on 2023-06-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0002_alter_review_models_dt_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_models',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
        migrations.AlterField(
            model_name='review_models',
            name='ratings',
            field=models.IntegerField(choices=[(1, '★'), (3, '★★★'), (2, '★★'), (5, '★★★★★'), (4, '★★★★')]),
        ),
    ]
