# Generated by Django 4.2.2 on 2023-06-24 01:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0003_alter_review_models_imgfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_models',
            name='imgfile',
            field=models.ImageField(upload_to='review_images/', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='review_models',
            name='ratings',
            field=models.IntegerField(choices=[(3, '★★★'), (4, '★★★★'), (1, '★'), (5, '★★★★★'), (2, '★★')]),
        ),
    ]
