# Generated by Django 4.2.2 on 2023-06-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0007_alter_review_models_imgfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_models',
            name='objects_clf',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='review_models',
            name='ratings',
            field=models.IntegerField(choices=[(4, '★★★★'), (1, '★'), (5, '★★★★★'), (2, '★★'), (3, '★★★')]),
        ),
    ]
