# Generated by Django 4.2.2 on 2023-06-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0010_delete_usermodel_alter_review_models_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_models',
            name='ratings',
            field=models.IntegerField(choices=[(5, '★★★★★'), (2, '★★'), (4, '★★★★'), (1, '★'), (3, '★★★')]),
        ),
    ]
