# Generated by Django 4.2.2 on 2023-06-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0012_alter_review_models_imgfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_models',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review_models',
            name='ratings',
            field=models.IntegerField(choices=[(2, '★★'), (3, '★★★'), (5, '★★★★★'), (1, '★'), (4, '★★★★')]),
        ),
    ]
