# Generated by Django 4.2.2 on 2023-06-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0013_alter_review_models_dt_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_models',
            name='objects_clf',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review_models',
            name='ratings',
            field=models.IntegerField(choices=[(4, '★★★★'), (5, '★★★★★'), (1, '★'), (2, '★★'), (3, '★★★')]),
        ),
    ]
