# Generated by Django 4.2.2 on 2023-06-27 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0014_alter_review_models_objects_clf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_models',
            name='imgfile',
            field=models.ImageField(upload_to='review_images/', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='review_models',
            name='ratings',
            field=models.IntegerField(choices=[(2, '★★'), (1, '★'), (4, '★★★★'), (3, '★★★'), (5, '★★★★★')]),
        ),
    ]
