# Generated by Django 4.2.2 on 2023-06-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0015_alter_review_models_imgfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_models',
            name='ratings',
            field=models.IntegerField(choices=[(5, '★★★★★'), (1, '★'), (3, '★★★'), (4, '★★★★'), (2, '★★')]),
        ),
    ]
