# Generated by Django 4.2.2 on 2023-06-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0019_review_models_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_models',
            name='ratings',
            field=models.IntegerField(choices=[(5, '⭐️⭐️⭐️⭐️⭐️'), (4, '⭐️⭐️⭐️⭐️'), (3, '⭐️⭐️⭐️'), (2, '⭐️⭐️'), (1, '⭐️')]),
        ),
    ]
