# Generated by Django 4.2.2 on 2023-06-29 11:28

import Reviews.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0020_alter_review_models_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_models',
            name='imgfile',
            field=models.ImageField(upload_to=Reviews.models.rename_imagefile_to_uuid, validators=[django.core.validators.validate_image_file_extension, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'], message='다음과 같은 형식의 확장자만 사용 가능합니다(jpg, png, jpeg)')]),
        ),
        migrations.AlterField(
            model_name='review_models',
            name='objects_clf',
            field=models.CharField(max_length=1000),
        ),
    ]
